---
configure_public_yum_repo: false
configure_motd: false

autostartup_service: true

configure_hugepages_by: memory

# disable hugepages on small systems
# don't forget to enable use_large_pages in oracle parameter
# size_in_gb_hugepages: 2
size_in_gb_hugepages: 0
